In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
gfi= pd.read_excel(r'C:\Users\vandu\Downloads\gfi.xlsx')

In [3]:
gfi.rename(columns = {'Unnamed: 0':'Year'}, inplace = True)

In [4]:
gfi.set_index('Year', inplace=True)

In [5]:
gfi

Green Credit  Green Securities  Green Investment1  Green Investment 2
Year                                                                       
2011     402653.83         688662.52              40.00                1500
2012     788501.40         969829.12              42.00                1676
2013     926211.91        1189667.10              57.72                1366
2014    1094724.35        1646633.94              57.72                2296
2015    1296977.64        1770653.43              52.00                1656
2016    1613891.38        1866861.40              50.00                1790
2017    1971634.98        2705363.32              65.00                1545
2018    2264898.66        3372310.26              74.30                2390
2019    2619541.91        3922412.36             100.00                4115
2020    3211896.00        5386655.75             100.00                4191
2021    3333775.64        6263059.73             100.00                3030

# Normalization 

In [6]:
for column in gfi:
    gfi[column]= (gfi[column] - gfi[column].mean())/gfi[column].std()

In [7]:
gfi

Green Credit  Green Securities  Green Investment1  Green Investment 2
Year                                                                       
2011     -1.387629         -1.097326          -1.172590           -0.801369
2012     -0.997477         -0.944497          -1.086237           -0.630033
2013     -0.858230         -0.825003          -0.407506           -0.931818
2014     -0.687838         -0.576618          -0.407506           -0.026462
2015     -0.483328         -0.509206          -0.654474           -0.649503
2016     -0.162879         -0.456912          -0.740827           -0.519053
2017      0.198856         -0.001142          -0.093182           -0.757561
2018      0.495391          0.361379           0.308357            0.065048
2019      0.853990          0.660389           1.417988            1.744338
2020      1.452953          1.456283           1.417988            1.818324
2021      1.576192          1.932655           1.417988            0.688089

In [8]:
V = gfi.cov()
V

Green Credit  Green Securities  Green Investment1  \
Green Credit            1.000000          0.979490           0.941811   
Green Securities        0.979490          1.000000           0.940902   
Green Investment1       0.941811          0.940902           1.000000   
Green Investment 2      0.805455          0.798047           0.894232   

                    Green Investment 2  
Green Credit                  0.805455  
Green Securities              0.798047  
Green Investment1             0.894232  
Green Investment 2            1.000000

In [9]:
from numpy import linalg as LA
w,v=LA.eig(V)

In [10]:
w

array([3.68328484, 0.25558593, 0.02035802, 0.04077121])

In [11]:
v

array([[ 0.50680493,  0.39517363,  0.69645087,  0.31928474],
       [ 0.50572004,  0.42105261, -0.7150642 ,  0.23589222],
       [ 0.51301767, -0.05352369,  0.04915542, -0.85529634],
       [ 0.47350699, -0.81467031, -0.03497318,  0.33298692]])

In [12]:
sum=0
for i in w:
    sum=sum+i

In [13]:
v[0]

array([0.50680493, 0.39517363, 0.69645087, 0.31928474])

In [14]:
from sklearn.decomposition import PCA
 
pca = PCA(n_components = 1)
 
gfi = pca.fit_transform(gfi) 
explained_variance = pca.explained_variance_ratio_

In [15]:
gfi=pd.DataFrame(gfi)

In [16]:
gfi

0
0  -2.239210
1  -1.838761
2  -1.502456
3  -0.861794
4  -1.145770
5  -0.939450
6  -0.306311
7   0.622816
8   2.320188
9   3.061277
10  2.829472